### ISSUE TITLE
Lita::Handlers::Spendo crashed.

### ISSUE THREAD

**Issue by digitaljedi2** [chalfant/lita-spendo#1]
I'm using lita-slack (slack bot) and have configured evreything accordingly, when I message my bot with `spendo nickname` I get the following.

[2015-06-01 16:04:10 UTC] ERROR: Lita::Handlers::Spendo crashed. The exception was:
undefined method `+' for nil:NilClass
Full backtrace:
/var/lib/gems/2.0.0/gems/lita-spendo-0.4.1/lib/lita/handlers/spendo.rb:116:in`create_message'
/var/lib/gems/2.0.0/gems/lita-spendo-0.4.1/lib/lita/handlers/spendo.rb:75:in `show'
/var/lib/gems/2.0.0/gems/lita-4.3.2/lib/lita/callback.rb:31:in`public_send'
/var/lib/gems/2.0.0/gems/lita-4.3.2/lib/lita/callback.rb:31:in `call'
/var/lib/gems/2.0.0/gems/lita-4.3.2/lib/lita/handler/chat_router.rb:88:in`dispatch_to_route'
/var/lib/gems/2.0.0/gems/lita-4.3.2/lib/lita/handler/chat_router.rb:73:in `block in dispatch'
/var/lib/gems/2.0.0/gems/lita-4.3.2/lib/lita/handler/chat_router.rb:70:in`map'
/var/lib/gems/2.0.0/gems/lita-4.3.2/lib/lita/handler/chat_router.rb:70:in `dispatch'
/var/lib/gems/2.0.0/gems/lita-4.3.2/lib/lita/robot.rb:58:in`block in receive'
/usr/lib/ruby/2.0.0/set.rb:232:in `each_key'
/usr/lib/ruby/2.0.0/set.rb:232:in`each'
/var/lib/gems/2.0.0/gems/lita-4.3.2/lib/lita/robot.rb:55:in `map'
/var/lib/gems/2.0.0/gems/lita-4.3.2/lib/lita/robot.rb:55:in`receive'
/var/lib/gems/2.0.0/gems/lita-slack-1.4.0/lib/lita/adapters/slack/message_handler.rb:58:in `dispatch_message'
/var/lib/gems/2.0.0/gems/lita-slack-1.4.0/lib/lita/adapters/slack/message_handler.rb:93:in`handle_message'
/var/lib/gems/2.0.0/gems/lita-slack-1.4.0/lib/lita/adapters/slack/message_handler.rb:17:in `handle'
/var/lib/gems/2.0.0/gems/lita-slack-1.4.0/lib/lita/adapters/slack/rtm_connection.rb:97:in`block in receive_message'
/var/lib/gems/2.0.0/gems/lita-slack-1.4.0/lib/lita/adapters/slack/event_loop.rb:9:in `block in defer'
/var/lib/gems/2.0.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:1054:in`call'
/var/lib/gems/2.0.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:1054:in `block in spawn_threadpool'

**Comment by chalfant** [comment]
Have you set the base_image_url config option in your lita_config.rb file?

**Comment by digitaljedi2** [comment]
This is my lita_config.rb

```
config.handlers.spendo.accounts = [ {
                          'nickname'              => 'prod',
                          'aws_account_id'        => ENV['AWS_ACCOUNT_ID'],
                          'aws_access_key_id'     => ENV['AWS_ACCESS_KEY_ID'],
                          'aws_secret_access_key' => ENV['AWS_SECRET_ACCESS_KEY'],
                          'aws_region'            => 'us-east-1',
                          'room'                  => '#general', # or room JID or whatever
                          'dynamodb_table'        => 'BillingHistory',
                          'time_between_polls'        => '1800',
                          'base_image_url'        => 'http://bigboysclub.com.au/wp-content/uploads/clown-thumb.jpg'
                    } ]
```

**Comment by chalfant** [comment]
Try moving the base_image_url out of the accounts hash to a first-class
configuration option.

That configuration value should be a url prefix to a directory of images
named 1.jpg, 2.jpg, etc. Spendo will post a link to the image based on the
alert level (1 = 25% nominal, 2 = 50% nominal, 3 = 75% nominal and so on).

Maybe I should change it to explicitly set the image URL for each level...

This could definitely be made more clear in the README.

# http://myscaryclownimages.com/1.jpg

# http://myscaryclownimages.com/2.jpg

# ...

config.handlers.spendo.base_image_url = 'http://
http://bigboysclub.com.au/wp-content/uploads/clown-thumb.jpg
myscaryclownimages.com'

Love the clown, BTW.

**Comment by digitaljedi2** [comment]
Ahh much better.  looks like it's just documentation interpretation issues :).  No more stack trace, all looks good.  I notice for 'slack' it just posts the URL to the channel and doesn't actually post the picture, I'm not sure if that's intended, or a new issue.

**Comment by chalfant** [comment]
I've only used this plugin with hipchat. There may be modifications we can make to be slack-friendly. Feel free to submit PRs!

Thanks for trying out the plugin. Our guys fear spendo and his relentless hatred of runaway AWS bills. I hope he instills the same fear in your team.

**Comment by digitaljedi2** [comment]
Ok.  Is there a way to know 'when' you are in a slack hander from within the route?   I can submit a PR for some formatting and handling and such, if I can figure out when we're in 'slack' or 'hc'

**Comment by chalfant** [comment]
I'm actually not sure. 

There may be a way to interrogate the 'robot' object from within the spendo plugin to find out what adapter it's using (robot.registry.adapters maybe?). Or we could just hand that in as a config (which seems kind of hacky).

**Comment by digitaljedi2** [comment]
Let me tinker with it and see what I can do.   I'll see what objects are avail and fix up some formatting in lib/

**Comment by digitaljedi2** [comment]
so a pp on my install for robot.registry.adapters returns
{:shell=>Lita::Adapters::Shell, :slack=>Lita::Adapters::Slack}
Can you dump yours? and Perhaps I can make some crafty formatting based on adapters.
